-- 1. Create a table to store the short links
create table short_links (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  slug text unique not null,
  destination_url text not null,
  owner_email text,
  click_count int default 0
);

-- 2. Create a table to log every click (Analytics Power)
create table link_clicks (
  id bigint generated by default as identity primary key,
  link_id bigint references short_links(id),
  ip_address text,
  user_agent text,
  country text,
  device_type text,
  referer text,
  clicked_at timestamp default now()
);

-- 3. Create a secure function to increment clicks (RPC)
create or replace function increment_click_count(row_id bigint)
returns void as $$
begin
  update short_links
  set click_count = click_count + 1
  where id = row_id;
end;
$$ language plpgsql security definer;
